# Generated by seedpod

UNAME_S := $(shell uname -s)
ifeq ($(UNAME_S),Darwin)
    CXX = clang++
    PATH:=/opt/oblong/deps-64-8/bin:$(PATH)
    MAGICKFLAGS = \
	-I/opt/oblong/deps-64-8/include/ImageMagick \
	-I.. \
	-DMAGICKCORE_HDRI_ENABLE=0 \
	-DMAGICKCORE_QUANTUM_DEPTH=16 \
        -lMagick++6-Q16 -lMagickCore6-Q16
else
    PATH:=/opt/oblong/deps/bin:$(PATH)
    MAGICKFLAGS = \
	$(shell pkg-config --libs --cflags ImageMagick++) \
	-DMAGICKCORE_HDRI_ENABLE=0 \
	-DMAGICKCORE_QUANTUM_DEPTH=16
endif

GH_PATH=/opt/oblong/greenhouse
GH_PKG_CONFIG=$(PKG_CONFIG_PATH):$(GH_PATH)/lib/pkgconfig pkg-config

CXXFLAGS = -Wempty-body \
  -fdiagnostics-show-option \
  -Wall \
  -Wpointer-arith \
  -Wno-shadow \
  -Wwrite-strings \
  -Wno-overloaded-virtual \
  -Wno-strict-overflow \
  -Wno-error=unused-variable \
  -Werror \
  `PKG_CONFIG_PATH=$(GH_PKG_CONFIG) --cflags --static libGreenhouse` \
  -g -O3 -std=gnu++0x

LDFLAGS=`PKG_CONFIG_PATH=$(GH_PKG_CONFIG) --libs --static libGreenhouse`

esc=`echo "\033"`
NO_COLOR=${esc}[0m
OK_COLOR=${esc}[36;21m

define EXP_STR

Build succeeded.

=======================================================================
To have your application find assets in a folder of your choice
(such as your current folder), you can append directories to the
ob_share_path environment variable.

This style affects just one run of the program:

   OB_SHARE_PATH=/Users/foo/images:$$OB_SHARE_PATH ./my-program

This style affects the current terminal session:

   export OB_SHARE_PATH=`pwd`/share:$$OB_SHARE_PATH

    ('pwd' is just minor terminal trickiness here that
    	substitutes in the name of the current directory)
=======================================================================
endef
export EXP_STR

all: alpha-hackathon
clean:
	-rm alpha-hackathon

alpha-hackathon: alpha-hackathon.C
	${CXX} $^ ${LDFLAGS} ${MAGICKFLAGS} -lGreenhouse -lboost_thread -lboost_system -lboost_filesystem ${CXXFLAGS} -o $@
	@echo	"$(OK_COLOR)$$EXP_STR$(NO_COLOR)"
